# Setup
title:               Lennart Grosser
tagline:             'Blog'
description:         ''
url:
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Lennart Grosser
  url:
  email:             lennart.grosser@web.de

# Gems
plugins:
  - jekyll-paginate
  
# Custom vars
version:             0.1
google_analytics_id: #UA-XXXX-Y
